const mongoose = require("mongoose");

const mortalityRecordSchema = new mongoose.Schema(
  {
    mortalityId: {
      type: String,
      unique: true,
      sparse: true,
      trim: true,
    },

    date: {
      type: Date,
      required: true,
    },

    batchId: {
      type: String,
      required: true,
      trim: true,
    },

    numberOfMortality: {
      type: Number,
      required: true,
      min: 1,
    },

    causeOfDeath: {
      type: String,
      required: true,
      trim: true,
    },

    suspectedDisease: {
      type: String,
      default: "",
      trim: true,
    },

    remarks: {
      type: String,
      default: "",
      trim: true,
      maxlength: 500,
    },

    autoGeneratedFromCulling: {
      type: Boolean,
      default: false,
    },

    sourceIsolationId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "QuarantineIsolation",
      default: null,
    },

    // Computed by backend
    currentBirds: {
      type: Number,
      default: 0,
      min: 0,
    },

    mortalityRate: {
      type: Number,
      default: 0,
      min: 0,
    },

    archived: {
      type: Boolean,
      default: false,
    },

    archivedAt: {
      type: Date,
      default: null,
    },
  },
  {
    timestamps: true,
  }
);

module.exports = mongoose.model(
  "MortalityRecord",
  mortalityRecordSchema
);
