const MortalityRecord = require("../models/MortalityRecord");
const Flock = require("../models/Flock");
const QuarantineIsolation = require("../models/QuarantineIsolation");
const { createAuditLog } = require("./auditController");
const { createArchiveEntry } = require("./archiveController");
const { createNotification } = require("./notificationController");
const { resolveHealthOption } = require("./healthOptionController");
const Archive = require("../models/Archive");

const isAutomaticallyGenerated = async (mortalityRecord) => {
  if (
    mortalityRecord.autoGeneratedFromCulling ||
    mortalityRecord.sourceIsolationId
  ) {
    return true;
  }

  return Boolean(
    await QuarantineIsolation.exists({
      "progressUpdates.mortalityRecordId": mortalityRecord._id,
    })
  );
};

const serializeMortalityRecord = async (mortalityRecord) => {
  const record = mortalityRecord.toObject();
  record.autoGeneratedFromIsolation = Boolean(
    mortalityRecord.sourceIsolationId
  ) || Boolean(
    await QuarantineIsolation.exists({
      "progressUpdates.mortalityRecordId": mortalityRecord._id,
    })
  );
  return record;
};

const generateMortalityId = async () => {
  const records = await MortalityRecord.find({ mortalityId: { $regex: /^M-\d+$/ } })
    .select("mortalityId")
    .lean();

  let maxNumber = 0;
  for (const r of records) {
    const n = parseInt(r.mortalityId.replace("M-", ""), 10);
    if (!isNaN(n) && n > maxNumber) maxNumber = n;
  }

  let candidate = `M-${String(maxNumber + 1).padStart(3, "0")}`;
  let attempt = maxNumber + 1;
  while (await MortalityRecord.exists({ mortalityId: candidate })) {
    attempt += 1;
    candidate = `M-${String(attempt).padStart(3, "0")}`;
  }

  return candidate;
};

const computeMortalityStats = async (
  batchId,
  numberOfMortality = 0,
  excludeId = null
) => {
  const flock = await Flock.findOne({
    batchId,
    isArchived: false,
  });

  if (!flock) {
    throw new Error("Flock not found.");
  }

  const records = await MortalityRecord.find({
    batchId,
    archived: false,
    ...(excludeId && {
      _id: { $ne: excludeId },
    }),
  });

  const totalPreviousMortality = records.reduce(
    (sum, record) =>
      sum + Number(record.numberOfMortality || 0),
    0
  );

  const purchaseQty = Number(flock.quantityPurchased);

  const currentBirds = Math.max(
    0,
    purchaseQty - totalPreviousMortality
  );

  const totalMortality =
    totalPreviousMortality +
    Number(numberOfMortality);

  const mortalityRate =
    purchaseQty > 0
      ? Number(
          (
            (totalMortality / purchaseQty) *
            100
          ).toFixed(2)
        )
      : 0;

  return {
    flock,
    purchaseQty,
    currentBirds,
    totalMortality,
    mortalityRate,
  };
};

const refreshFlockStatistics = async (batchId) => {
  const flock = await Flock.findOne({
    batchId,
    isArchived: false,
  });

  if (!flock) return;

  const records = await MortalityRecord.find({
    batchId,
    archived: false,
  });

  const totalMortality = records.reduce(
    (sum, record) =>
      sum + Number(record.numberOfMortality || 0),
    0
  );

  flock.totalMortality = totalMortality;

  flock.currentQuantity = Math.max(
    0,
    Number(flock.quantityPurchased) -
      totalMortality
  );

  flock.mortalityRate =
    flock.quantityPurchased > 0
      ? Number(
          (
            (totalMortality /
              flock.quantityPurchased) *
            100
          ).toFixed(2)
        )
      : 0;

  await flock.save();
};

const createMortalityRecord = async (req, res) => {
  try {
    const {
      date,
      batchId,
      numberOfMortality,
      causeOfDeath,
      newCauseOfDeath,
      remarks,
    } = req.body;

    if (
      !date ||
      !batchId ||
      !numberOfMortality ||
      (!causeOfDeath && !(newCauseOfDeath && newCauseOfDeath.trim()))
    ) {
      return res.status(400).json({
        success: false,
        message:
          "Please fill in all required fields.",
      });
    }

    const resolvedCauseOfDeath = newCauseOfDeath && newCauseOfDeath.trim()
      ? await resolveHealthOption("causeOfDeath", newCauseOfDeath)
      : causeOfDeath;

    const existing =
      await MortalityRecord.findOne({
        date,
        batchId,
        archived: false,
      });

    if (existing) {
      return res.status(400).json({
        success: false,
        message:
          "A mortality record already exists for this Batch and Date.",
      });
    }

    const {
      currentBirds,
      mortalityRate,
    } = await computeMortalityStats(
      batchId,
      Number(numberOfMortality)
    );

    if (
      Number(numberOfMortality) >
      currentBirds
    ) {
      return res.status(400).json({
        success: false,
        message:
          "Number of mortality exceeds current birds.",
      });
    }

    const ongoingQuarantine = await QuarantineIsolation.findOne({
      batchId,
      recordType: "Quarantine",
      status: "Ongoing",
    });
    if (ongoingQuarantine) {
      if (Number(numberOfMortality) > ongoingQuarantine.headCount) {
        return res.status(400).json({
          success: false,
          message: `Number of mortality exceeds the current Quarantine Head Count (${ongoingQuarantine.headCount}).`,
        });
      }
      ongoingQuarantine.headCount = Math.max(0, ongoingQuarantine.headCount - Number(numberOfMortality));
      await ongoingQuarantine.save();
    }

    const mortalityId = await generateMortalityId();

    const mortalityRecord =
      await MortalityRecord.create({
        mortalityId,
        date,
        batchId,
        numberOfMortality,
        causeOfDeath: resolvedCauseOfDeath,
        remarks,

        currentBirds:
          currentBirds -
          Number(numberOfMortality),

        mortalityRate,
      });

    await refreshFlockStatistics(
      batchId
    );

    await createAuditLog({
      user: req.user.name,
      role: req.user.role,
      module: "Mortality Record",
      action: "Added",
      description: `Added mortality record for Batch ${batchId}.`,
      prev: null,
      next: mortalityRecord,
    });

    const deaths = Number(numberOfMortality);
    const pctToday = currentBirds > 0 ? (deaths / currentBirds) * 100 : 0;
    if (pctToday >= 5 || deaths >= 5) {
      const isSevere = pctToday >= 10 || deaths >= 10;
      await createNotification({
        title: "High Mortality Detected",
        description: `High mortality detected in Batch ${batchId}. ${deaths} bird(s) recorded today at ${new Date().toLocaleTimeString()}.`,
        category: "mortality",
        type: "alert",
        priority: isSevere ? "High" : "Normal",
        roles: ["Owner", "Farmer"],
      });
    }

    return res.status(201).json({
      success: true,
      message:
        "Mortality record created successfully.",
      record: mortalityRecord,
    });
  } catch (error) {
    console.error(error);

    return res.status(500).json({
      success: false,
      message:
        "Unable to create mortality record.",
      error: error.message,
    });
  }
};

const getAllMortalityRecords = async (req, res) => {
  try {
    const records = await MortalityRecord.find({
      archived: false,
    }).sort({
      createdAt: -1,
    });

    const serializedRecords = await Promise.all(
      records.map(serializeMortalityRecord)
    );

    return res.status(200).json({
      success: true,
      count: records.length,
      records: serializedRecords,
    });
  } catch (error) {
    console.error(error);

    return res.status(500).json({
      success: false,
      message: "Unable to retrieve mortality records.",
      error: error.message,
    });
  }
};

const getMortalityRecordById = async (req, res) => {
  try {
    const record = await MortalityRecord.findById(req.params.id);

    if (!record) {
      return res.status(404).json({
        success: false,
        message: "Mortality record not found.",
      });
    }

    const serializedRecord = await serializeMortalityRecord(record);

    return res.status(200).json({
      success: true,
      record: serializedRecord,
    });
  } catch (error) {
    console.error(error);

    return res.status(500).json({
      success: false,
      message: "Unable to retrieve mortality record.",
      error: error.message,
    });
  }
};

const updateMortalityRecord = async (req, res) => {
  try {
    const mortalityRecord = await MortalityRecord.findById(
      req.params.id
    );

    if (!mortalityRecord) {
      return res.status(404).json({
        success: false,
        message: "Mortality record not found.",
      });
    }

    const previousData = mortalityRecord.toObject();

    const {
      date,
      batchId,
      numberOfMortality,
      causeOfDeath,
      newCauseOfDeath,
      remarks,
    } = req.body;

    if (await isAutomaticallyGenerated(mortalityRecord)) {
      mortalityRecord.remarks = remarks ?? mortalityRecord.remarks;

      await mortalityRecord.save();

      await createAuditLog({
        user: req.user.name,
        role: req.user.role,
        module: "Mortality Record",
        action: "Edited",
        description: `Updated remarks for automatically generated mortality record for Batch ${mortalityRecord.batchId}.`,
        prev: previousData,
        next: mortalityRecord,
      });

      return res.status(200).json({
        success: true,
        message: "Mortality record remarks updated successfully.",
        record: mortalityRecord,
      });
    }

    const resolvedCauseOfDeath = newCauseOfDeath && newCauseOfDeath.trim()
      ? await resolveHealthOption("causeOfDeath", newCauseOfDeath)
      : causeOfDeath;

    if (
      mortalityRecord.sourceIsolationId &&
      batchId != null &&
      batchId !== mortalityRecord.batchId
    ) {
      return res.status(400).json({
        success: false,
        message: "This mortality record came from an Isolation event — change its Batch ID from the Isolation record instead.",
      });
    }

    const duplicate = await MortalityRecord.findOne({
      _id: { $ne: req.params.id },
      date,
      batchId,
      archived: false,
    });

    if (duplicate) {
      return res.status(400).json({
        success: false,
        message:
          "Another mortality record already exists for this Batch and Date.",
      });
    }

    const {
      currentBirds,
      mortalityRate,
    } = await computeMortalityStats(
      batchId,
      Number(numberOfMortality),
      req.params.id
    );

    if (
      Number(numberOfMortality) >
      currentBirds
    ) {
      return res.status(400).json({
        success: false,
        message:
          "Number of mortality exceeds current birds.",
      });
    }

    if (previousData.batchId) {
      const oldBatchQuarantine = await QuarantineIsolation.findOne({
        batchId: previousData.batchId,
        recordType: "Quarantine",
        status: "Ongoing",
      });
      if (oldBatchQuarantine) {
        oldBatchQuarantine.headCount += Number(previousData.numberOfMortality || 0);
        await oldBatchQuarantine.save();
      }
    }
    const newBatchQuarantine = await QuarantineIsolation.findOne({
      batchId,
      recordType: "Quarantine",
      status: "Ongoing",
    });
    if (newBatchQuarantine) {
      if (Number(numberOfMortality) > newBatchQuarantine.headCount) {
        return res.status(400).json({
          success: false,
          message: `Number of mortality exceeds the current Quarantine Head Count (${newBatchQuarantine.headCount}).`,
        });
      }
      newBatchQuarantine.headCount = Math.max(0, newBatchQuarantine.headCount - Number(numberOfMortality));
      await newBatchQuarantine.save();
    }

    mortalityRecord.date = date;
    mortalityRecord.batchId = batchId;
    mortalityRecord.numberOfMortality =
      Number(numberOfMortality);
    mortalityRecord.causeOfDeath =
      resolvedCauseOfDeath ?? mortalityRecord.causeOfDeath;
    mortalityRecord.remarks = remarks;

    mortalityRecord.currentBirds =
      currentBirds -
      Number(numberOfMortality);

    mortalityRecord.mortalityRate =
      mortalityRate;

    await mortalityRecord.save();

    await refreshFlockStatistics(
      batchId
    );
    if (previousData.batchId && previousData.batchId !== batchId) {
      await refreshFlockStatistics(previousData.batchId);
    }

    await createAuditLog({
      user: req.user.name,
      role: req.user.role,
      module: "Mortality Record",
      action: "Edited",
      description: `Updated mortality record for Batch ${batchId}.`,
      prev: previousData,
      next: mortalityRecord,
    });

    return res.status(200).json({
      success: true,
      message:
        "Mortality record updated successfully.",
      record: mortalityRecord,
    });
  } catch (error) {
    console.error(error);

    return res.status(500).json({
      success: false,
      message:
        "Unable to update mortality record.",
      error: error.message,
    });
  }
};

const deleteMortalityRecord = async (req, res) => {
  try {
    const mortalityRecord = await MortalityRecord.findById(
      req.params.id
    );

    if (!mortalityRecord) {
      return res.status(404).json({
        success: false,
        message: "Mortality record not found.",
      });
    }

    const batchId = mortalityRecord.batchId;

    await createAuditLog({
      user: req.user.name,
      role: req.user.role,
      module: "Mortality Record",
      action: "Deleted",
      description: `Deleted mortality record for Batch ${batchId}.`,
      prev: mortalityRecord,
      next: null,
    });

    await mortalityRecord.deleteOne();

    await Archive.findOneAndDelete({
     moduleKey: "pb_mortality",
     recordId: mortalityRecord._id,
    });

    await refreshFlockStatistics(batchId);

    return res.status(200).json({
      success: true,
      message: "Mortality record deleted successfully.",
    });
  } catch (error) {
    console.error(error);

    return res.status(500).json({
      success: false,
      message: "Unable to delete mortality record.",
      error: error.message,
    });
  }
};

const archiveMortalityRecord = async (req, res) => {
  try {
    const mortalityRecord = await MortalityRecord.findById(
      req.params.id
    );

    if (!mortalityRecord) {
      return res.status(404).json({
        success: false,
        message: "Mortality record not found.",
      });
    }

    mortalityRecord.archived = true;
    mortalityRecord.archivedAt = new Date();

    await mortalityRecord.save();

    await refreshFlockStatistics(
      mortalityRecord.batchId
    );

    await createArchiveEntry({
      module: "Mortality Record",
      moduleKey: "pb_mortality",
      recordId: mortalityRecord._id,
      recordName: `Batch ${mortalityRecord.batchId}`,
      archivedBy: req.user.name,
      payload: mortalityRecord.toObject(),
    });

    await createAuditLog({
      user: req.user.name,
      role: req.user.role,
      module: "Mortality Record",
      action: "Archived",
      description: `Archived mortality record for Batch ${mortalityRecord.batchId}.`,
      prev: null,
      next: mortalityRecord,
    });

    return res.status(200).json({
      success: true,
      message: "Mortality record archived successfully.",
    });
  } catch (error) {
    console.error(error);

    return res.status(500).json({
      success: false,
      message: "Unable to archive mortality record.",
      error: error.message,
    });
  }
};

const restoreMortalityRecord = async (req, res) => {
  try {
    const mortalityRecord = await MortalityRecord.findById(
      req.params.id
    );

    if (!mortalityRecord) {
      return res.status(404).json({
        success: false,
        message: "Mortality record not found.",
      });
    }

    mortalityRecord.archived = false;
    mortalityRecord.archivedAt = null;

    await mortalityRecord.save();

    await refreshFlockStatistics(
      mortalityRecord.batchId
    );

    await Archive.findOneAndDelete({
     moduleKey: "pb_mortality",
     recordId: mortalityRecord._id,
    });

    await createAuditLog({
      user: req.user.name,
      role: req.user.role,
      module: "Mortality Record",
      action: "Restored",
      description: `Restored mortality record for Batch ${mortalityRecord.batchId}.`,
      prev: null,
      next: mortalityRecord,
    });

    return res.status(200).json({
      success: true,
      message: "Mortality record restored successfully.",
    });
  } catch (error) {
    console.error(error);

    return res.status(500).json({
      success: false,
      message: "Unable to restore mortality record.",
      error: error.message,
    });
  }
};

const getArchivedMortalityRecords = async (
  req,
  res
) => {
  try {
    const records = await MortalityRecord.find({
      archived: true,
    }).sort({
      archivedAt: -1,
    });

    return res.status(200).json({
      success: true,
      count: records.length,
      records,
    });
  } catch (error) {
    console.error(error);

    return res.status(500).json({
      success: false,
      message:
        "Unable to retrieve archived mortality records.",
      error: error.message,
    });
  }
};

module.exports = {
  createMortalityRecord,
  getAllMortalityRecords,
  getMortalityRecordById,
  updateMortalityRecord,
  deleteMortalityRecord,
  archiveMortalityRecord,
  restoreMortalityRecord,
  getArchivedMortalityRecords,
  generateMortalityId,
};
